DELETE FROM routing_rules;

INSERT INTO routing_rules
(rule_name, description, rule_version, priority, active,
 intent_pattern, sentiment_pattern, urgency_pattern, keyword_patterns,
 assign_to_team, priority_override, sla_hours,
 created_at, updated_at)
VALUES

('Critical Security Incident', 
 'Route critical security breaches and compromised accounts to security team', 
 1, 100, true, 
 'SECURITY_INCIDENT|COMPROMISED_ACCOUNT|SUSPICIOUS_LOGIN|PHISHING', NULL, 'CRITICAL', NULL, 
 'security-team', 'CRITICAL', 1, 
 now(), now()),

('Critical Urgent Issues', 
 'Route critical urgent issues to senior support', 
 1, 95, true, 
 NULL, NULL, 'CRITICAL', NULL, 
 'senior-support', 'CRITICAL', 2, 
 now(), now()),

('High Urgency Negative Sentiment', 
 'Escalate urgent negative cases to prevent churn', 
 1, 90, true, 
 NULL, 'NEGATIVE', 'HIGH', NULL, 
 'escalation-team', 'HIGH', 4, 
 now(), now()),

('Technical High Priority', 
 'High urgency technical issues like application crashes', 
 1, 85, true, 
 'TECHNICAL|BUG_REPORT|APPLICATION_CRASH', NULL, 'HIGH', NULL, 
 'tech-support-senior', 'HIGH', 8, 
 now(), now()),

('API and Developer Support', 
 'Route API, webhook, and integration issues to developer support', 
 1, 80, true, 
 'API_INTEGRATION|WEBHOOK_ERROR|API_KEY_ISSUE|OAUTH|RATE_LIMIT', NULL, NULL, NULL, 
 'developer-support', 'MEDIUM', 12, 
 now(), now()),

('Data Privacy and GDPR', 
 'Route data privacy, GDPR, and account deletion requests to compliance', 
 1, 75, true, 
 'GDPR|DATA_DELETION|DATA_EXPORT|DATA_PRIVACY|RETENTION_POLICY', NULL, NULL, NULL, 
 'compliance-team', 'HIGH', 24, 
 now(), now()),

('Billing and Payment Issues', 
 'All billing, refund, duplicate charges, and invoice issues', 
 1, 70, true, 
 'BILLING|PAYMENT_ISSUE|CHECK_REFUND_STATUS|DUPLICATE_CHARGE|INVOICE|PAYMENT_FAILURE', NULL, NULL, NULL, 
 'billing-team', 'MEDIUM', 24, 
 now(), now()),

('Subscription Management', 
 'Plan upgrades, downgrades, cancellations, and renewals', 
 1, 65, true, 
 'SUBSCRIPTION|PLAN_UPGRADE|PLAN_DOWNGRADE|CANCELLATION|RENEWAL|FREE_TRIAL', NULL, NULL, NULL, 
 'billing-team', 'LOW', 48, 
 now(), now()),

('Account Access Issues', 
 'Account login, SSO, 2FA, and lockout problems', 
 1, 60, true, 
 'ACCOUNT|SSO|TWO_FACTOR|PASSWORD_RESET|LOCKOUT|EMAIL_VERIFICATION', NULL, NULL, NULL, 
 'account-team', 'HIGH', 12, 
 now(), now()),

('Technical Medium Priority', 
 'Medium urgency tech issues and slow performance', 
 1, 50, true, 
 'TECHNICAL|TROUBLESHOOTING|SLOW_PERFORMANCE|FILE_UPLOAD', NULL, 'MEDIUM', NULL, 
 'tech-support', 'MEDIUM', 24, 
 now(), now()),

('Feature Requests', 
 'Route feature requests and product feedback', 
 1, 40, true, 
 'FEATURE_REQUEST|FEEDBACK', NULL, NULL, NULL, 
 'product-team', 'LOW', 72, 
 now(), now()),

('Complaints', 
 'Customer complaints and dissatisfaction', 
 1, 30, true, 
 'COMPLAINT|DISSATISFIED', 'NEGATIVE', NULL, NULL, 
 'customer-success', 'MEDIUM', 24, 
 now(), now()),

('General Low Priority', 
 'General low urgency tickets and inquiries', 
 1, 20, true, 
 'GENERAL', NULL, 'LOW', NULL, 
 'general-support', 'LOW', 48, 
 now(), now()),

('Default Catch-All', 
 'Fallback routing for unmatched tickets', 
 1, 10, true, 
 NULL, NULL, NULL, NULL, 
 'general-support', 'MEDIUM', 24, 
 now(), now());