# Kubernetes Profile overrides

# 1. Connect to Postgres Service inside K8s
spring.datasource.url=jdbc:postgresql://postgres.ai-support.svc.cluster.local:5432/auth_db

# 2. Connect to Eureka Discovery Service inside K8s
eureka.client.service-url.defaultZone=http://discovery-service.ai-support.svc.cluster.local:8761/eureka
eureka.instance.prefer-ip-address=true
