package com.aisupport.orchestration.infrastructure;

import static org.assertj.core.api.Assertions.assertThat;
import static org.awaitility.Awaitility.await;

import java.time.Instant;
import java.util.HashMap;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.TimeUnit;

import org.junit.jupiter.api.Test;
import org.springframework.context.annotation.Import;

import com.aisupport.orchestration.application.workflow.WorkflowEngine;
import com.aisupport.orchestration.application.workflow.WorkflowExecutionResult;
import com.aisupport.orchestration.application.workflow.WorkflowStatus;
import com.aisupport.orchestration.domain.state.WorkflowState;
import com.aisupport.orchestration.infrastructure.messaging.publisher.OutboxEventPublisher;
import com.aisupport.orchestration.infrastructure.persistence.entity.OutboxEventEntity;
import com.aisupport.orchestration.infrastructure.persistence.entity.WorkflowCheckpointEntity;
import com.aisupport.orchestration.infrastructure.persistence.entity.WorkflowExecutionEntity;
import com.aisupport.orchestration.infrastructure.persistence.repository.OutboxEventRepository;
import com.aisupport.orchestration.infrastructure.persistence.repository.WorkflowCheckpointRepository;
import com.aisupport.orchestration.infrastructure.persistence.repository.WorkflowExecutionRepository;

import lombok.RequiredArgsConstructor;

@Import(TestAiConfiguration.class)
@RequiredArgsConstructor
class WorkflowRecoveryIT extends AbstractIntegrationTest {

    private final WorkflowEngine workflowEngine;

    private final WorkflowExecutionRepository workflowExecutionRepository;

    private final WorkflowCheckpointRepository workflowCheckpointRepository;

    private final OutboxEventRepository outboxEventRepository;

    private final OutboxEventPublisher outboxEventPublisher;

    @Test
    void testWorkflowRecoveryAndOutboxPublishing() {
        // Clean up any existing outbox events from previous tests
        outboxEventRepository.deleteAll();
        workflowExecutionRepository.deleteAll();
        workflowCheckpointRepository.deleteAll();
        
        // Given a simulated crashed execution
        String executionId = UUID.randomUUID().toString();
        String correlationId = UUID.randomUUID().toString();
        Long ticketId = System.currentTimeMillis(); // Use unique timestamp to avoid collisions

        WorkflowExecutionEntity execution = WorkflowExecutionEntity.builder()
                .id(executionId)
                .definitionId("analyze-workflow")
                .correlationId(correlationId)
                .ticketId(ticketId)
                .state(WorkflowState.CREATED)
                .createdAt(Instant.now())
                .updatedAt(Instant.now())
                .attributes(new HashMap<>())
                .build();
        workflowExecutionRepository.save(execution);

        // Simulated checkpoint after AssembleContextStep
        WorkflowCheckpointEntity checkpoint = WorkflowCheckpointEntity.builder()
                .execution(execution)
                .stepName("AssembleContextStep")
                .stateSnapshot(WorkflowState.RUNNING)
                .attributesSnapshot(new HashMap<>())
                .createdAt(Instant.now())
                .build();
        workflowCheckpointRepository.save(checkpoint);

        // When we resume the execution
        WorkflowExecutionResult result = workflowEngine.resume(executionId);

        // Then it should complete successfully
        assertThat(result.getStatus()).isEqualTo(WorkflowStatus.SUCCESS);

        WorkflowExecutionEntity updatedExecution = workflowExecutionRepository.findById(executionId).orElseThrow();
        assertThat(updatedExecution.getState()).isEqualTo(WorkflowState.COMPLETED);
        
        // It should have incremented the recovery count
        assertThat(updatedExecution.getRecoveryCount()).isEqualTo(1);

        // Then an outbox event should be generated by the listener
        await().atMost(5, TimeUnit.SECONDS).untilAsserted(() -> {
            List<OutboxEventEntity> outboxEvents = outboxEventRepository.findAll().stream()
                    .filter(e -> e.getAggregateId().equals(ticketId.toString()))
                    .toList();
            assertThat(outboxEvents).hasSize(1);
            assertThat(outboxEvents.get(0).getEventType()).isEqualTo("TicketOrchestratedEvent");
        });

        // When the publisher runs
        outboxEventPublisher.publishEvents();

        // Then the outbox event should be published and deleted for this ticket
        List<OutboxEventEntity> remainingEvents = outboxEventRepository.findAll().stream()
                .filter(e -> e.getAggregateId().equals(ticketId.toString()))
                .toList();
        assertThat(remainingEvents).isEmpty();
    }
}









