# ============================================
# APPLICATION CONFIGURATION
# ============================================
spring.application.name=AI-ANALYSIS-SERVICE
server.port=8083

# ===============================================
# ACTIVE PROFILE
# ===============================================
spring.profiles.active=local

# ===============================================
# MICROSERVICE API URLS
# ===============================================
api.ticket.service.url=http://TICKET-SERVICE:8082