# ============================================
# APPLICATION CONFIGURATION (GCP)
# ============================================
server.port=${PORT:8761}


# ============================================
# ACTUATOR CONFIGURATION
# ============================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.info.env.enabled=false


# ============================================
# DASHBOARD CONFIGURATION
# ============================================
eureka.dashboard.enabled=true


# ============================================
# EUREKA SERVER CONFIGURATION (GCP)
# ============================================
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=true
eureka.server.eviction-interval-timer-in-ms=5000


# ============================================
# LOG LEVELS (Info-friendly)
# ============================================
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO

