# ============================================
# APPLICATION CONFIGURATION
# ============================================
spring.application.name=DISCOVERY-SERVICE
server.port=8761

# ===============================================
# ACTIVE PROFILE
# ===============================================
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# ===============================================
# EUREKA SERVER CONFIGURATION
# ===============================================
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=true
eureka.server.eviction-interval-timer-in-ms=5000

# ===============================================
# DASHBOARD CONFIGURATION
# ===============================================
eureka.dashboard.enabled=true

# ===============================================
# LOG LEVELS (Info-friendly)
# ===============================================
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO
