# ============================================
# COMMON CONFIGURATION
# ============================================
spring.jpa.open-in-view=false


# ============================================
# ACTUATOR INFO
# ============================================
info.app.name=@project.name@
info.app.version=@project.version@
info.app.description=@project.description@
info.app.environment=${spring.profiles.active}


# ============================================
# OPENAPI CONFIGURATION
# ============================================
springdoc.api-docs.version=OPENAPI_3_0
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html