# ============================================
# APPLICATION CONFIGURATION
# ============================================
spring.application.name=ticket-service
server.port=8082

# ===============================================
# Active Profile
# ===============================================
spring.profiles.active=local

# ===============================================
# Microservice API Endpoints
# ===============================================
