# ===============================================
# Spring Boot Application Name
# ===============================================
spring.application.name=ticket-service

# ===============================================
# Server Configuration
# ===============================================
server.port=9092

# ===============================================
# Spring Boot Default Profile
# ===============================================
spring.profiles.active=local

# ===============================================
# Microservice API Endpoints
# ===============================================
