# ===============================================
# Database Configuration
# ===============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_service
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================================
# Hibernate Configuration
# ===============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.show-sql=true

# ===============================================
# Jackson Configuration
# ===============================================
spring.jackson.time-zone=Asia/Kolkata

# ===============================================
# Eureka Client Configuration
# ===============================================
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost

# ===============================================
# Log Levels (Debug-friendly)
# ===============================================
logging.level.root=INFO
#logging.level.com.aisupport.ticket=DEBUG
#logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=WARN

# ===============================================
# File Output
# ===============================================
logging.file.name=./logs/${spring.application.name}.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=3
