# Kubernetes Profile overrides

# 1. Connect to Postgres Service inside K8s
spring.datasource.url=jdbc:postgresql://postgres.ai-support.svc.cluster.local:5432/ticket_db

# 2. Connect to Eureka Discovery Service inside K8s
eureka.client.service-url.defaultZone=http://discovery-service.ai-support.svc.cluster.local:8761/eureka
eureka.instance.prefer-ip-address=true

# 3. Connect to Kafka internal listener
spring.kafka.bootstrap-servers=kafka.ai-support.svc.cluster.local:9092
