# ============================================
# APPLICATION CONFIGURATION
# ============================================
spring.application.name=TICKET-SERVICE
server.port=8082

# ===============================================
# ACTIVE PROFILE
# ===============================================
spring.profiles.active=local

# ================================================
# ACTUATOR INFO
# ================================================
info.app.name=@project.name@
info.app.version=@project.version@
info.app.description=@project.description@
info.app.environment=${spring.profiles.active}

# ===============================================
# MICROSERVICE API URLS (Discovered via Eureka)
# ===============================================
api.services.ai-analysis.url=http://AI-ANALYSIS-SERVICE
api.services.routing.url=http://ROUTING-SERVICE
api.services.rag.url=http://RAG-SERVICE